apiVersion: types.kubefed.io/v1beta1
kind: FederatedIngress
metadata:
  name: test-ingress
  namespace: geko-demo
spec:
  template:
    spec:
      rules:
        - host: ingress.example.com
          http:
            paths:
              - backend:
                  serviceName: test-service
                  servicePort: 80
  placement:
    clusters:
      - name: kubefed-demo2
      - name: kubefed-demo1
