apiVersion: types.kubefed.io/v1beta1
kind: FederatedConfigMap
metadata:
  name: geko-way
  namespace: geko-demo
spec:
  template:
    data:
      index.html: "Feel the Geko way!"
  placement:
    clusters:
      - name: kubefed-demo2
      - name: kubefed-demo1




apiVersion: v1
kind: ConfigMap
metadata:
  name: geko-way
data:
  index.html: "Feel the Geko way!"
  
  
  
  
  



